name: Build, Package, and Push to Feed

on:
  push:
    branches: [ "master" ]

env: 
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/dynamicscrm/Solutions/_packaging/Solutions-SmartPlacesAndEnergy/nuget/v3/index.json    
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  WORKING_DIRECTORY: OntologyMapper
  DOTNET_VERSION: '6.x' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }} 

      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore "${{ env.WORKING_DIRECTORY }}"
          dotnet build "${{ env.WORKING_DIRECTORY }}" -c '${{ env.BUILD_CONFIGURATION }}'
          dotnet pack "${{ env.WORKING_DIRECTORY }}" -c '${{ env.BUILD_CONFIGURATION }}' --version-suffix $GITHUB_RUN_ID
      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push --api-key AzureArtifacts OntologyMapper/src/bin/Release/*.nupkg
